paths:
  data_root: "/home/beatly-digital/Documents/indresh/FULL_DATA_MIMIC"
  index_csv: "data/index.csv"
  runs_dir: "runs"
  export_dir: "export"

data:
  fs: 125                # <— was 100; your windows are 1250 samples in 10 s
  win_seconds: 10
  normalize: "zscore"
  bandpass: [0.5, 8.0]
  channels:              # <— NEW: multi-channel inputs
    raw: true
    vel: true            # dPPG (1st derivative)
    acc: true            # SDPPG (2nd derivative)
  sqi:
    enable: true
    amp_range: [0.1, 3.0]
    flat_std_min: 0.05
    hr_range: [40, 180]
  augment:
    enable: true
    time_warp_pct: 0.02  # gentler: preserves SBP-critical morphology
    amp_scale_pct: 0.10
    jitter_std: 0.003
    crop_seconds: 0.0
    time_mask:
      enable: true
      max_frac: 0.08

cv:
  n_splits: 5
  seed: 42

train:
  batch_size: 128
  num_workers: 6
  epochs: 100
  optimizer: "adamw"
  lr: 0.001
  weight_decay: 0.001     # ↑ regularization
  scheduler: "cosine"
  warmup_epochs: 5
  grad_clip: 1.0
  early_stop_patience: 20
  loss: "hetero"          # <— switch to heteroscedastic loss
  sbp_weight: 1.5         # ↑ emphasize SBP
  ema:
    enable: true
    decay: 0.999

# ... keep paths, data, cv, train as you have (fs=125, channels raw+vel+acc can be ignored by BeatFormer)

model:
  name: "UNet1D"
  in_channels: 3            # raw + vel + acc
  cnn_channels: [32, 64, 128, 256]
  kernel_size: 7
  se_reduction: 8
  head_hidden: 256
  dropout: 0.2


beats:
  target_len: 256         # resample each beat to this length
  max_beats: 16           # pad/truncate beat sequence to this many beats per 10 s
  min_beats: 6            # skip windows with too few valid beats during TRAIN
  peak_distance_ms: 300   # min peak distance
  prominence: 0.1         # peak prominence for find_peaks
  use_vel_acc: true       # build 3 channels: raw, dPPG, SDPPG
